### PR TITLE
Adding moveit_* packages (retry)

### PR DESCRIPTION
**Pull request by 130s**
They are currently git submodules, which is not intended.

### CODE REVIEW

**Comment by 130s** [comment]
@davetcoleman @IanTheEngineer
I'm just trying to aggregate as many MoveIt! packages as possible into a single repo.

I'm in process of making a new release of MoveIt! https://github.com/ros-planning/moveit_ros/issues/662 Working with packages distributed into multiple repositories, each of which takes significant amount of time for the prerelease test and build on the ROS buildfarm https://github.com/ros-planning/moveit_msgs/issues/18#issuecomment-209750986 is a painful process (I know I'm being very cautious since this is the 1st time).

So, I'm now very much fond of the aggregation idea Dave mentioned in ROSCon2015.

Since in PR form it's kind of hard how the entire folder structure looks, so I merge it for the better view, despite the error in Travis that I for now don't pay much attention to what causes it. See https://github.com/130s/moveit for such a folder structure.

And Travis line hasn't even reached the limit with the nice output (10K lines), which is nice.

Hope this helps to start a conversation. Feel free to include whoever you need to.

Aimingu Kinetic release may be too ambitious? (we need to update Jade too)

**Comment by davetcoleman** [comment]
Yes, I still really want to do this, I think it would make maintaining MoveIt! _SO_ much more manageable for us maintainers. Thoughts:
- SRDFdom probably should stay separate so that non-MoveIt! packages can easily use it
- @ferguson has argued that moveit_msgs should stay separate too for other packages to easily communicate with moveit without depending on all of it
- This move would need to be a very concerted effort because it will break everyone's forks, branches, pending PRs
- We should probably do a big push to close as many open PRs as possible before doing this
- I think we could target Kinetic...

**Comment by 130s** [comment]
Thanks for the feedback @davetcoleman 
Currently the time I can spend on MoveIt! is taken by jade release but once I'm done with I can work on this.
Also I like to pull in @rhaschke to this loop.

**Comment by 130s** [comment]
> - SRDFdom probably should stay separate so that non-MoveIt! packages can easily use it
> - @ferguson has argued that moveit_msgs should stay separate too for other packages to easily communicate with moveit without depending on all of it

WIP at https://github.com/130s/moveit/pull/3

**Pull request merged**
